name: 'Update dependencies reminder'
on:
  schedule:
    - cron: 1/15 * * * *

jobs:
  weekly-report:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout workspace
      uses: actions/checkout@master

    # Get date and store as environment variables
    - name: Get and store variables
      run: |
        echo ::set-env name=BRANCH_NAME::$(date +%F)
        echo ::set-env name=WEEK_OF::"Week of $(date '+%B %d, %Y')"
        
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build --if-present
    - run: npm audit fix || true
    - run: npm test
      env:
        CI: true

    # Create meeting notes scaffold
    - name: Create weekly notes scaffold file
      run:  |
        for f in docs/changelog.md
        do
        sed -i '/# Changelog/a\
        ## '"$WEEK_OF"'\
        \
        ### What is changed ? \
        \
        - [TODO]' $f
        \
        \
        done

    # Push changes and set env variable for branch name
    - name: Commit and push notes scaffold to branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git config --global user.email $GITHUB_ACTOR@users.noreply.github.com
        git config --global user.name $GITHUB_ACTOR
        git checkout -b $BRANCH_NAME
        git add .
        git diff-index --quiet HEAD || commit -m "Please check you dependencies"
        git push --force --set-upstream "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" $BRANCH_NAME
    # Open pull request
    - name: Open pull request for reminder
      uses: actions/github-script@0.4.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const createPull = await github.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: process.env["WEEK_OF"],
            body: "",
            head: process.env["BRANCH_NAME"],
            base: "master",
            draft: true
          });
          github.issues.addAssignees({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: createPull.data.number,
            assignees: [
              "semihgokduman"
            ],
          });
